### ISSUE TITLE
Sprache für Anfänger und Mädchen anpassen

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/organize#4]
Wie das Coder Dojo Bonn gesagt hat: 
- statt "programmieren" konkrete Beispiele geben, im Fokus soll stehen, was erreicht werden kann, wozu man befähigt wird, nicht welches Mittel genutzt wird. Beispiel:
  
  > CoderDojo ist ein Club für Mädchen und Jungen im Alter von 5 bis 17 Jahren, die eigene Spiele bauen, Roboter steuern, Programmieren lernen und Spass haben wollen.
- statt Kinder&Jugendliche "Mädchen und Jungen"

Das sollte überall eingepflegt werden:
- Plakate
- Webseite zen
- Eventbrite

**Comment by Natureshadow** [comment]
Was ist das denn für ein Unsinn?

Wieso verstehen Mädchen denn das Wort "programmieren" nicht?

Bitte unterlasst doch die Diskriminierung.

**Comment by niccokunzmann** [comment]
@Natureshadow Danke für den Hinweis. Der Titel wurde geändert. Da ich Unsinn schreibe, fände ich es gut, wenn Deine Anregung darauf eingeht, was ich verbessern kann, da ich sonst aus meinem Standpunkt durch negatives Feedback nur wieder raten kann.

**Comment by Natureshadow** [comment]
OK, etwas ausführlicher:

Zum Thema Diskriminierung hast du den fehler ja schon halbwegs erkannt. Nun steht da „Anfänger und Mädchen“. Das ist zwar immerhin eine Änderung, aber immer noch nicht besser.

Das Grundproblem ist folgendes: Irgendwann vor ein paar Jahren haben ein paar aufmerksame Menschen bemerkt, dass wir darauf achten müssen, _auch_ Mädchen (und Frauen) stärker in IT-Berufe und ähnliches zu integrieren und für MINT zu begeistern. Das ist gut gemeint - aber wie so oft im Leben endet es in vielen Fällen mit gut gemeint, gut gemacht wird es nur selten.

Die Grenze zwischen Gleichstellung, Bevorzugung und Diskriminierung ist nämlich etwas dünner als ein Haar. Mit deiner Formulierung hier unterstellst du zwei Dinge:
1. Mädchen sind Anfänger
2. Mädchen udn andere Anfänger brauchen Babysprache

Dass es nichts mit Gleichstellung oder minimierten Hürden zu tun hat, wenn ich schon in der Überschrift die Begriffe „Mädchen“ und „Anfänger“ in einen Topf werfe, ist denke ich ziemlich offensichtlich. Damit bewegen wir uns im Bereich der Alltagsdiskriminierung. Alltagsdiskriminierung von (vermeintlich) Schwächeren begegnet uns jeden Tag. Wenn man etwas darauf achtet, ist sie leicht zu erkennen. Beispiele:
- Dieser Issue
- Die Verwendung des Begriffs „Jugendliche“ als Synonym für „mir unbekannte, eher respektlose junge Menschen“
- Ungefragte Hilfestellung (= Bevormundung), natürlich nur außerhalb von Notsituationen
- …

Wenn ich also jemandem ungefragt „Leichte Sprache“ oder übereilt eine Hilfestellung anbiete, dann diskriminiere oder bevormunde ich. Wir müssen als Gesellschaft lernen - und zwar in allen Altersstufen - Probleme, die wir haben und bei denen wir Hilfe brauchen, zu benennen und auf der anderen Seite anderen gut zuzuhören und sensibel zu beobachten, was notwendig ist.

Das ist natürlich besonders in der Pädagogik äußerst wichtig. Wir haben erkannt, dass Inklusion z.B. nicht funktioniert, wenn wir Unterricht und Arbeitsumgebung an unser Verständnis des „normalen“ Schülers anpassen. Ebenso wenig funktioniert es aber, wenn wir alles an die aus usnerer Sicht „schwachen“ Schüler anpassen.

Und deshalb ist es wichtig, klare Hilfsmöglichkeiten anzubieten, die jeder genau dann nutzen kann, wenn er sie braucht. Das kann dann aber jeder selber entscheiden.

Zurück zum case at hand: Mädchen zu bevormunden, weil sie unsere Sprache vermeintlich nicht können, ist Unsinn und echte Alltagsdiskriminierung. Für „Anfänger“ gilt aber dasselbe.

Ein konkreter Lösungsansatz: Die Tätigkeit, die du vermitteln möchtest, heißt „Programmieren“. Punkt, Ende, also schreibst du das da auch hin. Wenn du glaubst, es gibt Menschen, die dazu eine Erklärung brauchen, dann baue ein kleines Glossar in die Fußnote, wo man dann nachlesen kann.

**Comment by kirstin** [comment]
Lieber Dominik,
1. Diese Diskussion geht am Problem vorbei.
2. Das Problem ist, seit über einem Jahr kommen signifikant weniger Mädchen als Jungen. Es sind ungefähr 90% Jungen.
3. Wir haben nach bestem Wissen keinen Unterschied zwischen den Geschlechtern gemacht. Es hat auch keinen Unterschied in der Anzahl der Mädchen gemacht.
4. Nicco möchte die Strategie verändern: Mädchen sollen direkter angesprochen werden

Nicco würde gerne mit dir telefonieren, damit du den Kontext des Coder Dojo Potsdam besser verstehen kannst. Du kannst ihm eine E-mail mit deiner Telefonnummer senden oder nach seiner Telefonnummer suchen. 
Ich denke hier ist ein Gespräch von Nöten bei dem man sich gegenseitig austauscht und dieses ist der falsche Informationskanal, um so ein Gespräch zu führen.

**Comment by Natureshadow** [comment]
Nicco hat meine Kontaktdaten. Meine Meinung wird sich aber durch ein Gespräch nicht ändern.

Den Kanal habt ihr ja gewählt. Wenn ihr einen öffentlichen Issue-Tracker befüllt, müsst ihr mit öffentlicher Diskussion rechnen - dafür ist der ja da.

**Comment by Natureshadow** [comment]
Aber mal ganz davon ab - die neueste Formulierung oben in der Issue-Beschreibung ist doch perfekt und enthält alles, was ich kritisiert habe. Deshalb sehe ich weder ein weiteres Problem noch Klärungsbedarf (außer dem Titel - Vorschlag: „Erklärende Sprache“, ohne Referenz zu Anfänger oder Mädchen)

**Comment by niccokunzmann** [comment]
Hallo Dominik. Was oben stand war die ganze Zeit gemeint. 

Mit @kirstin s Worten:

> Du hast den Post nicht verstanden, dich aber nicht darum bemüht, Fragen zu stellen und heraus zu finden, was wir meinen. Du hast unangenehm provoziert und beleidigt. 

Ich hätte mir gewünscht, dass dein Unwissen für uns angenehmer gewesen wäre. Dass es öffentlich ist, heißt nicht, dass es für jeden Kontext bestimmt ist. Понятно? 

Das ist Verwarnung 1.

Ich finde es gut, dass wir die Missverständnisse ausgeräumt haben und hoffe, dass wir in Zukunft angenehm kommunizieren. Wir ziehen ja beide am selben Strang :+1:

**Comment by Natureshadow** [comment]
> Ich hätte mir gewünscht, dass dein Unwissen […]

Unwissen? Soso. Nein, deine ursprüngliche Formulierung _war_ diskriminierend und völlig am Ziel vorbei. Dass ich denke, dass das keine Absicht war, sollte aus dem zweiten Post erkennbar sein. Aber gut gemeint ist nicht gut gemacht, und die gesamte Formulierung war Humbug. Nichts anderes habe ich kritisiert.

Offenbar stimmst du dem ja auch zu, sonst hättest du es ja nicht geändert.

Wenn du damit nicht leben kannst, dann poste bitte keine Diskussionsaufrufe.

> Das ist Verwarnung 1.

Ah ja :D. Na dann.

**Comment by Natureshadow** [comment]
Damit die Diskussion wieder nachvollziehbar ist (der Original-Post wurde so weit editiert, dass er zwar jetzt in Ordnung ist, aber niemand mehr den Grund für die Diskussion erkennt):

Die ursprüngliche Formulierung war „Sprache für Mädchen anpassen“ und „statt "programmieren" bauen oder machen".

**Comment by niccokunzmann** [comment]
Please comment if you like to re-open the issue.
