### ISSUE TITLE
Informatik Biber & Bundeswettbewerb Informatik

### ISSUE THREAD

**Issue by friedow** [CoderDojoPotsdam/organize#8]
Informatik Biber direkt beim nächsten Coder Dojo!

BWInf Erinnerung für alle & Anstoß des Projektes beim Coder Dojo.

**Comment by niccokunzmann** [comment]
BWINf habe ich schon an die, die es lange machen verbreitet. Vielleicht ist der Informatikbieber für die anderen gut.

http://informatik-biber.de/
7.-11. November steht auf der Webseite.

**Comment by niccokunzmann** [comment]
Ich habe mich mal als Lehrer im CoderDojo beim BWINF registriert. Ich bin mit der ÖA im Kontakt, ob die schon was zum  bieber machen.

**Comment by niccokunzmann** [comment]
Die Briefe werden irgendwann am HPI ankommen mit den Urkunden.
