### ISSUE TITLE
Webseite verlinkt auf 404 Fehler

### ISSUE THREAD

**Issue by GittiHab** [CoderDojoPotsdam/organize#9]
Hallo Leute, die von GitHub verlinkte Seite (https://CoderDojoPotsdam.github.io) kommt auf einen 404 Fehler bei der CoderDojo Seite raus. Wollen die Admins das bitte ändern 😉.

Neue URL auf CoderDojo.com: https://zen.coderdojo.com/dojo/de/brandenburg/potsdam/potsdam-hpi

**Comment by niccokunzmann** [comment]
@GittiHab magst du die Seite editieren? Hier ist ein Beispielcommit: https://github.com/CoderDojoPotsdam/CoderDojoPotsdam.github.io/commit/417dc027b0bce7366acc1e5a03104bef3255978d

Du kannst sie immer ändern, wenn dir das auffällt. Club-Mitglieder haben Schreibrechte.

**Comment by GittiHab** [comment]
Danke, dass du es gemacht hast. Bin leider nicht mehr dazu gekommen.
